/*
 * CarbonAware.WebApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

import (
	"time"
)

type EmissionsDataDto struct {
	Location  string    `json:"location,omitempty"`
	Timestamp time.Time `json:"timestamp,omitempty"`
	Duration  int32     `json:"duration,omitempty"`
	Value     float64   `json:"value,omitempty"`
}
