/*
 * CarbonAware.WebApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

import (
	"time"
)

type EmissionsData struct {
	Location string    `json:"location,omitempty"`
	Time     time.Time `json:"time,omitempty"`
	Rating   float64   `json:"rating,omitempty"`
	Duration string    `json:"duration,omitempty"`
}
