apiVersion: v1
kind: Pod
metadata:
 name: keda-carbon-exporter
spec:
 containers:
 - name: exporter
   image: ghcr.io/azure/kubernetes-carbon-intensity-exporter/exporter:0.1.0
   imagePullPolicy: Always
   ports:
   - containerPort: 7031
