apiVersion: v1
kind: Pod
metadata:
 name: server
spec:
 containers:
 - name: server
   image: ghcr.io/Azure/carbon-intensity-exporter/server:0.1.0
   imagePullPolicy: Always
   command: [
     "sh",
     "-c",
     "cd /app && sed \"s/username/wibuchan/g\" -i appsettings.json && sed \"s/password/greenAI/g\" -i appsettings.json && dotnet CarbonAware.WebApi.dll",
    ]
   ports:
   - containerPort: 7031
